import {
  bannerone
} from '@/assets/png';

export const banners = [
  {
    id: 1,
    imageUrl: bannerone,
    alt: 'image-1',
  },
  // {
  //   id: 2,
  //   imageUrl: bannertwo,
  //   alt: 'image-2',
  // },
  // {
  //   id: 3,
  //   imageUrl: bannerthree,
  //   alt: 'image-3',
  // },
  // {
  //   id: 4,
  //   imageUrl: banner1,
  //   alt: 'image-4',
  // },
  // {
  //   id: 5,
  //   imageUrl: banner2,
  //   alt: 'image-5',
  // },
  // {
  //   id: 6,
  //   imageUrl: banner3,
  //   alt: 'image-6',
  // },
];

export const CASINO_TEMP_IMAGES = [
  'https://fungamess.games/images/games/yjow4Z3A7NYOHK4r13VeWnEMX0FJ5LjP3bRUNjen.png',
  'https://fungamess.games/images/games/7njoz7bMVlLyKX2pWAhg5wetPWZuO2OzpuAF8tjR.png',
  'https://fungamess.games/images/games/DNRTaqrP5sbY5FyLlWkzh6CsXfYbM9bNqyqfe2lb.png',
  'https://fungamess.games/images/games/QqwgcpjniYZohHa43o5TN6TZkggEDSUdHILyuqOM.png',
  'https://fungamess.games/images/games/SshVRJsHLDXDQW1kER1LNUqRwVAswziPojQ0PVu2.png',
  'https://fungamess.games/images/games/6tKcjbA9trEG5nz7T7YeochldyCgvR99GlPNpwRl.png',
  'https://fungamess.games/images/games/SZDuZfhHbTDSQg0jALg77rXDtpmWtkXR3pXdUFam.png',
  'https://fungamess.games/images/games/sSsXwJbnP5f77ZR7C8B1ArEMRQ938je5hdkEKLcK.png',
  'https://fungamess.games/images/games/fy1dNpQYwJPpzVYAGGZ3rGJrg5wy2DGPBf4YYmxv.png',
  'https://fungamess.games/images/games/SmNpSGpPBoMKPwwJNV0IXSPYJvz2dpTKoKinR7Ca.png',
  'https://fungamess.games/images/games/pquJy8fGp4HsU6u8T9cukSDva774yPKXjWJNM7fH.png',
  'https://fungamess.games/images/games/Dn6brPPFcuJ8FNoD706a2qM28g7mThqwb8R55xLB.png',
  'https://fungamess.games/images/games/srwTfbUx0h19DYgSKbx9pgoOf7iRtuBV4d7OX4mF.png',
  'https://fungamess.games/images/games/QPlbWy97lOtK1IiQDK643Qp6ao1o9wmeTN6he5C8.png',
  'https://fungamess.games/images/games/7oFCFKPmsa6mgrNK6XhGxlAKT6NW5LSS50TFeefU.png',
  'https://fungamess.games/images/games/d3a0PoO5wtG5brXkWIoXjuo1HFMiRNZKhaWsTVY3.png',
  'https://fungamess.games/images/games/RIqRhZVTOGXvcbPQLWbDajgyE88oe1bQzXLgJFN0.png',
  'https://fungamess.games/images/games/XcYbmFGQ5Dy9rMYQIqkjEuvtAv5xaUTt3wy3Mdmz.png',
  'https://fungamess.games/images/games/MjrZjn6OHD6Kv5TRfaPeGYKs2af8lfBVne4H9y4I.png',
  'https://fungamess.games/images/games/D3wjO2Un7BjpvMhvuBCarbIbSxnU4BYSQMkoffR9.png',
  'https://fungamess.games/images/games/ZWmWpF02lEiKtXMJV2KtLo5IGk0NEPmpTdMXDu5a.png',
  'https://fungamess.games/images/games/W9YPCFK2OLsWMbtgOYjGEomfZNV9d9IFFtt1TLeA.png',
  'https://fungamess.games/images/games/59bFrNt422cVDknvzfmSEk6nOuDtY9sZaRohcpFP.png',
  'https://fungamess.games/images/games/LAl1lV8oiSjexW7eUlhjJSgTho2EVQQxl3fp9Sfn.png',
  'https://fungamess.games/images/games/s34dGrL7XdS9XceOSnz8KtH3xUA2DL02w6pCX378.png',
  'https://fungamess.games/images/games/ZUtXEPhH1gwEwOAZbeUR7NXvYkBqVQ1UrksyrRFk.png',
  'https://fungamess.games/images/games/2wvQkDn6ArblZeAlpi0PNb4Q65gTkRpr9wDBL061.png',
  'https://fungamess.games/images/games/Ba7hHzA3mttxeCffc9genG7Ly2Mx4UCwAF34zeL3.png',
  'https://fungamess.games/images/games/3McMAVwAlxLmt3RbfKcVyv10ex0inWumuYJUGBlZ.png',
  'https://fungamess.games/images/games/eHqyyN3GE9xgtKh3GByY9wQ6wFMTCOt1DHDRYTcZ.png',
  'https://fungamess.games/images/games/TzMeqtJpZeL9XhDCv7qQFpQoLRF9tdCpAfTg5N7x.png',
  'https://fungamess.games/images/games/WyEHlB0AJWD1CjTdLXUtbt6yAFN0DWe1xtKgRWLO.png',
  'https://fungamess.games/images/games/r3HOg6ewyuONdM1PF5dbjLAMEX7EwJPAlHgpgFe1.png',
  'https://fungamess.games/images/games/uzQGwWRWZJ5I6mzgAxXt43JsGw6FIVCTY5FU5qNn.png',
  'https://fungamess.games/images/games/VWZwbHtDxA27Fl5bbea4S6MbV4YAuKmUpdKNvQ7C.png',
  'https://fungamess.games/images/games/UrNL9uxx58XC5eu0SZElFAtMWdM1NxTfbmb4WAN6.png',
  'https://fungamess.games/images/games/HjtBajS5mQLCc5YQC7MdCA5K1QyAp2jtX3osMHvg.png',
  'https://fungamess.games/images/games/ojzHqtApCwyE1dFnXDIkSX6iMRSel1Jnlr8VgBaM.png',
  'https://fungamess.games/images/games/06JfzCUk5sdJB6xixYBzQnwPBmhCHZfK7skRpRLx.png',
  'https://fungamess.games/images/games/5SBxB7VI2FQe3cHCkyExV2JPFDeNv35LzUqm0yWW.png',
  'https://fungamess.games/images/games/134q8f7q1lCQS0QDiby8tfWx3NxNJLrfdKgaZl1h.png',
  'https://fungamess.games/images/games/zOmUgKTrVWSMAWE4FwEE3DROTdjjMjcjxJ8kjBTa.png',
  'https://fungamess.games/images/games/Mw2kCSCf2UTn1ourX9eplA1tmLZtjCmBCQ5yRlQI.png',
  'https://fungamess.games/images/games/l49LzxpEUCPJESD0DDHUk95ySV3lZMMW4masgTQX.png',
  'https://fungamess.games/images/games/TjuU8VjDN6HqluAEHp6ynWlFH528flLCTW68s9Fh.png',
  'https://fungamess.games/images/games/dnfrLkBvMFhEifGKIFiGXv6UJf6NPMFHgVOx3sBB.png',
  'https://fungamess.games/images/games/mL9JRynje7pKRk2G4GV9EvQRS81wn8FR7yTvs9cE.png',
  'https://fungamess.games/images/games/sptbAfA5RjVsQYmL9sSZsM6sZth3bQ1qSDI4iMut.png',
];
