import { avatar1, avatar2, avatar3 } from '@/assets/png';
import { chatRuleIcon, gems, notice, rain, task } from '@/assets/svg';
export const GLOBAL_CHAT_ID = 'GLOBAL';
export const GIF_TENOR_API_KEY = 'AIzaSyBkymM920sb1FC_jOfSfDCkhu_IXgtWu1k';
export const chatNavBtnData = [
  {
    id: 1,
    icon: gems,
    path: '/',
    tooltip: 'Tip',
    buttonType: 'tips',
  },
  {
    id: 2,
    icon: rain,
    path: '/',
    tooltip: 'Rain',
    buttonType: 'rains',
  },
  {
    id: 3,
    icon: notice,
    path: '/',
    tooltip: 'Notice',
    newNotification: true,
    buttonType: 'notice',
  },
  // {
  //   id: 4,
  //   icon: task,
  //   path: '/',
  //   tooltip: 'Task',
  //   value: true,
  //   buttonType: 'task',
  // },
  {
    id: 4,
    icon: chatRuleIcon,
    path: '/',
    tooltip: 'ChatRule',
    buttonType: 'chatRule',
  },
  // {
  //   id: 5,
  //   icon: peoples,
  //   path: '/',
  //   tooltip: 'Friends',
  // },
];

export const chatData = [
  {
    id: 1,
    level: 1,
    username: 'dinerosweeps bot',
    time: '03:27 PM',
    avatar: avatar1,
    isBot: true,
    isVerified: false,
    isVip: false,
    vipLevel: 0,
    mentionedUser: '',
    message:
      'Anybody up and feeling generous??? Sure could use a little blessing',
  },
  {
    id: 2,
    level: 22,
    username: 'Brandzicho',
    time: '03:28 PM',
    avatar: avatar2,
    isBot: false,
    isVerified: true,
    isVip: true,
    vipLevel: 2,
    mentionedUser: '',
    message: 'Good luck everyone!',
  },
  {
    id: 3,
    level: 15,
    username: 'pik1337',
    time: '03:29 PM',
    avatar: avatar3,
    isBot: false,
    isVerified: false,
    isVip: false,
    vipLevel: 1,
    mentionedUser: 'Brandzicho',
    message: 'Nice hit mate!',
  },
  {
    id: 4,
    level: 19,
    username: 'ziara',
    time: '03:30 PM',
    avatar: avatar1,
    isBot: false,
    isVerified: false,
    isVip: true,
    vipLevel: 1,
    mentionedUser: '',
    message: 'Good luck!',
  },
  {
    id: 5,
    level: 25,
    username: 'HighRoller92',
    time: '03:31 PM',
    avatar: avatar2,
    isBot: false,
    isVerified: true,
    isVip: true,
    vipLevel: 3,
    mentionedUser: 'pik1337',
    message: 'Congrats on that hit!',
  },
  {
    id: 6,
    level: 5,
    username: 'LuckyDuck',
    time: '03:32 PM',
    avatar: avatar3,
    isBot: false,
    isVerified: false,
    isVip: false,
    vipLevel: 0,
    mentionedUser: '',
    message: 'Wow, this room is on fire!',
  },
  {
    id: 7,
    level: 17,
    username: 'MeganP6333',
    time: '03:33 PM',
    avatar: avatar1,
    isBot: false,
    isVerified: true,
    isVip: true,
    vipLevel: 1,
    mentionedUser: 'ziara',
    message: 'Thanks for the luck!',
  },
  {
    id: 8,
    level: 2,
    username: 'NewbieKing',
    time: '03:34 PM',
    avatar: avatar2,
    isBot: false,
    isVerified: false,
    isVip: false,
    vipLevel: 0,
    mentionedUser: 'HighRoller92',
    message: 'Any tips for a new player?',
  },
  {
    id: 9,
    level: 30,
    username: 'DiamondHands',
    time: '03:35 PM',
    avatar: avatar3,
    isBot: false,
    isVerified: true,
    isVip: true,
    vipLevel: 4,
    mentionedUser: '',
    message: 'Keeping it cool and calm. Let’s go!',
  },
  {
    id: 10,
    level: 10,
    username: 'JaneDoe',
    time: '03:36 PM',
    avatar: avatar1,
    isBot: false,
    isVerified: false,
    isVip: false,
    vipLevel: 0,
    mentionedUser: 'DiamondHands',
    message: 'You make it look easy!',
  },
  {
    id: 11,
    level: 18,
    username: 'CryptoQueen',
    time: '03:37 PM',
    avatar: avatar2,
    isBot: false,
    isVerified: true,
    isVip: true,
    vipLevel: 2,
    mentionedUser: '',
    message: 'Feeling lucky today! Let’s win big!',
  },
  {
    id: 12,
    level: 27,
    username: 'TheAlchemist',
    time: '03:38 PM',
    avatar: avatar3,
    isBot: false,
    isVerified: true,
    isVip: false,
    vipLevel: 0,
    mentionedUser: 'CryptoQueen',
    message: 'Betting big on red this round?',
  },
  {
    id: 13,
    level: 5,
    username: 'GreenhornJoe',
    time: '03:39 PM',
    avatar: avatar1,
    isBot: false,
    isVerified: false,
    isVip: false,
    vipLevel: 0,
    mentionedUser: 'TheAlchemist',
    message: 'Any tips for a newbie?',
  },
  {
    id: 14,
    level: 20,
    username: 'JackpotJerry',
    time: '03:40 PM',
    avatar: avatar2,
    isBot: false,
    isVerified: true,
    isVip: true,
    vipLevel: 3,
    mentionedUser: '',
    message: 'Congrats',
  },
  {
    id: 15,
    level: 8,
    username: 'SneakyFox',
    time: '03:41 PM',
    avatar: avatar1,
    isBot: false,
    isVerified: false,
    isVip: false,
    vipLevel: 1,
    mentionedUser: 'JackpotJerry',
    message: 'Congrats! Hoping to hit my first big one soon!',
  },
  {
    id: 16,
    level: 35,
    username: 'LadyLuck',
    time: '03:42 PM',
    avatar: avatar2,
    isBot: false,
    isVerified: true,
    isVip: true,
    vipLevel: 4,
    mentionedUser: '',
    message: 'Luck is on my side today!',
  },
  {
    id: 17,
    level: 3,
    username: 'BeginnerBen',
    time: '03:43 PM',
    avatar: avatar3,
    isBot: false,
    isVerified: false,
    isVip: false,
    vipLevel: 0,
    mentionedUser: 'LadyLuck',
    message: 'Care to share some of that luck?',
  },
  {
    id: 18,
    level: 26,
    username: 'RiskyBusiness',
    time: '03:44 PM',
    avatar: avatar1,
    isBot: false,
    isVerified: true,
    isVip: true,
    vipLevel: 3,
    mentionedUser: '',
    message: 'Big risks, big rewards!',
  },
  {
    id: 19,
    level: 14,
    username: 'SilentWarrior',
    time: '03:45 PM',
    avatar: avatar2,
    isBot: false,
    isVerified: false,
    isVip: true,
    vipLevel: 1,
    mentionedUser: 'RiskyBusiness',
    message: 'Going all-in tonight?',
  },
  {
    id: 20,
    level: 7,
    username: 'LuckyLuke',
    time: '03:46 PM',
    avatar: avatar3,
    isBot: false,
    isVerified: false,
    isVip: true,
    vipLevel: 1,
    mentionedUser: '',
    message: 'Here’s hoping for some beginner’s luck!',
  },
];
export const GROUP_CHAT = [
  {
    message: 'Hello, World!',
    userId: '11',
    recipientId: '1',
    messageId: '5',
    gif: null,
    isContainOffensiveWord: false,
    messageType: 'MESSAGE',
    sharedEvent: {},
    createdAt: '2025-01-07T10:45:00.522Z',
    user: {
      username: 'yshak',
      profileImage: null,
    },
    replyMessage: null,
    tip: null,
  },
  // {
  //   message: 'Hello, World!',
  //   userId: '11',
  //   recipientId: '1',
  //   messageId: '13',
  //   gif: null,
  //   isContainOffensiveWord: false,
  //   messageType: 'MESSAGE',
  //   sharedEvent: {},
  //   createdAt: '2025-01-07T10:59:46.275Z',
  //   user: {
  //     username: 'yshak',
  //     profileImage: null,
  //   },
  //   replyMessage: {
  //     message: null,
  //     userId: '11',
  //     recipientId: null,
  //     messageId: '1',
  //     gif: null,
  //     isContainOffensiveWord: false,
  //     messageType: 'EVENT',
  //     sharedEvent: {},
  //     createdAt: '2025-01-07T10:01:21.710Z',
  //     user: {
  //       username: 'yshak',
  //       profileImage: null,
  //     },
  //     recipientUser: null,
  //     tip: null,
  //   },
  //   tip: null,
  // },
  // {
  //   message: 'Deleted because of offensive content.',
  //   userId: '11',
  //   recipientId: '1',
  //   messageId: '14',
  //   gif: null,
  //   isContainOffensiveWord: true,
  //   messageType: 'MESSAGE',
  //   sharedEvent: {},
  //   createdAt: '2025-01-07T11:04:35.124Z',
  //   user: {
  //     username: 'yshak',
  //     profileImage: null,
  //   },
  //   replyMessage: {
  //     message: null,
  //     userId: '11',
  //     recipientId: null,
  //     messageId: '1',
  //     gif: null,
  //     isContainOffensiveWord: false,
  //     messageType: 'EVENT',
  //     sharedEvent: {},
  //     createdAt: '2025-01-07T10:01:21.710Z',
  //     user: {
  //       username: 'yshak',
  //       profileImage: null,
  //     },
  //     recipientUser: null,
  //     tip: null,
  //   },
  //   tip: null,
  // },
  {
    message: 'Deleted because of offensive content.',
    userId: '11',
    recipientId: '1',
    messageId: '15',
    gif: null,
    isContainOffensiveWord: true,
    messageType: 'MESSAGE',
    sharedEvent: {},
    createdAt: '2025-01-07T11:05:58.532Z',
    user: {
      username: 'yshak',
      profileImage: null,
    },
    replyMessage: {
      message: null,
      userId: '11',
      recipientId: null,
      messageId: '1',
      gif: null,
      isContainOffensiveWord: false,
      messageType: 'EVENT',
      sharedEvent: {},
      createdAt: '2025-01-07T10:01:21.710Z',
      user: {
        username: 'yshak',
        profileImage: null,
      },
      recipientUser: null,
      tip: null,
    },
    tip: null,
  },
  {
    message: 'Deleted because of offensive content.',
    userId: '11',
    recipientId: '1',
    messageId: '16',
    gif: null,
    isContainOffensiveWord: true,
    messageType: 'MESSAGE',
    sharedEvent: {},
    createdAt: '2025-01-07T11:11:45.100Z',
    user: {
      username: 'yshak',
      profileImage: null,
    },
    replyMessage: {
      message: 'Deleted because of offensive content.',
      userId: '11',
      recipientId: '1',
      messageId: '14',
      gif: null,
      isContainOffensiveWord: true,
      messageType: 'MESSAGE',
      sharedEvent: {},
      createdAt: '2025-01-07T11:04:35.124Z',
      user: {
        username: 'yshak',
        profileImage: null,
      },
      recipientUser: {
        username: 'demo-user-1',
        userId: 1,
      },
      tip: null,
    },
    tip: null,
  },
];
