import TranslationsProvider from '@/components/TranslationProvider';
import { Toaster } from '@/components/ui/toaster';
import { StateProvider } from '@/store';
import { dir } from 'i18next';
import localFont from 'next/font/local';
import Head from 'next/head';
import { Suspense } from 'react';
import i18nConfig from '../../../i18nConfig';
import initTranslations from '../i18n';
import './global.scss';
import Image from 'next/image';
import { Loading } from '@/assets/png';
import RouteChangeLoader from '@/components/RouteChangeLoader';
// import AuthGuard from '@/components/AuthGuard';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata = {
  title: 'Dinero Sweeps',
  description: 'Generated by Dinero Sweeps',
  openGraph: {
    title: 'Dinero Sweeps',
    description: 'Play and win with Dinero Sweeps!',
    url: 'dinerosweeps.com',
    siteName: 'Dinero Sweeps',
    locale: 'en_US',
    type: 'website',
  },
  other: {
    'facebook-domain-verification': 'myu3koq5l98ay1476n5h380ecwtski',
  },
};

const i18nNamespaces = ['home'];

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  const { resources } = await initTranslations(locale, i18nNamespaces);

  return (
    <html
      lang={locale}
      dir={dir(locale)}
      className={`${geistSans.variable} ${geistMono.variable} `}
    >
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body className="antialiased h-full" suppressHydrationWarning>
        {/* pixi integration for wheel spin */}
        <script src="/assets/pixi-assets/js/pixi-legacy.min.js" defer />
        {/* <CustomOrionStarLoading /> */}
        <main>
          <Suspense
            fallback={
              <div className='w-svw h-svh flex items-center justify-center'>
                <Image src={Loading} alt="Loading" width={300} height={300} />
              </div>
            }
          >
            <StateProvider>
              <TranslationsProvider
                namespaces={i18nNamespaces}
                locale={locale}
                resources={resources}
              >
                <RouteChangeLoader />
                {/* <AuthGuard> */}
                  {children}
                {/* </AuthGuard> */}
              </TranslationsProvider>
              <Toaster />
            </StateProvider>
          </Suspense>
        </main>
      </body>
    </html>
  );
}
