export const SOCKET_EVENTS = {
  WALLET: 'USER_WALLET',
  WALLET_BALANCE: 'USER_WALLET_BALANCE',
  LIVE_USER_CHATS: 'LIVE_USER_CHATS',
  SEND_MESSAGE: 'SEND_MESSAGE',
  LIVE_CHAT_RAIN: 'LIVE_CHAT_RAIN',
  RECENT_BIG_WIN: 'RECENT_BIG_WIN',
};
