export const CASINO_TEMP_FAV_IMAGES = [
    'https://fungamess.games/images/games/yjow4Z3A7NYOHK4r13VeWnEMX0FJ5LjP3bRUNjen.png',
    'https://fungamess.games/images/games/LAl1lV8oiSjexW7eUlhjJSgTho2EVQQxl3fp9Sfn.png',
    'https://fungamess.games/images/games/s34dGrL7XdS9XceOSnz8KtH3xUA2DL02w6pCX378.png',
    'https://fungamess.games/images/games/ZUtXEPhH1gwEwOAZbeUR7NXvYkBqVQ1UrksyrRFk.png',
    'https://fungamess.games/images/games/06JfzCUk5sdJB6xixYBzQnwPBmhCHZfK7skRpRLx.png',
    'https://fungamess.games/images/games/5SBxB7VI2FQe3cHCkyExV2JPFDeNv35LzUqm0yWW.png',
    'https://fungamess.games/images/games/134q8f7q1lCQS0QDiby8tfWx3NxNJLrfdKgaZl1h.png',
    'https://fungamess.games/images/games/zOmUgKTrVWSMAWE4FwEE3DROTdjjMjcjxJ8kjBTa.png',
    'https://fungamess.games/images/games/Mw2kCSCf2UTn1ourX9eplA1tmLZtjCmBCQ5yRlQI.png',
    'https://fungamess.games/images/games/l49LzxpEUCPJESD0DDHUk95ySV3lZMMW4masgTQX.png',
    'https://fungamess.games/images/games/TjuU8VjDN6HqluAEHp6ynWlFH528flLCTW68s9Fh.png',
    'https://fungamess.games/images/games/dnfrLkBvMFhEifGKIFiGXv6UJf6NPMFHgVOx3sBB.png',
    'https://fungamess.games/images/games/mL9JRynje7pKRk2G4GV9EvQRS81wn8FR7yTvs9cE.png',
    'https://fungamess.games/images/games/sptbAfA5RjVsQYmL9sSZsM6sZth3bQ1qSDI4iMut.png',
  ];