name: Deploy to EC2

on:
  push:
    branches:
      - main   # runs only when code pushed to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/dinerosweeps

            # Ensure env setup
            if [ -f ./frontend/.env.production ]; then
              cp ./frontend/.env.production ./frontend/.env.local
            fi

            # Run your deployment script
            ./deploy.sh
